CREATE TABLE public.cards_expanded (
    name character varying(400),
    layout character varying(50),
    cmc integer,
    colors jsonb,
    color_identity jsonb,
    type character varying(200),
    supertypes jsonb,
    types jsonb,
    subtypes jsonb,
    rarity character varying(50),
    set character varying(10),
    set_name character varying(100),
    text text,
    flavor text,
    artist character varying(100),
    number character varying(20),
    power character varying(20),
    toughness character varying(20),
    loyalty character varying(20),
    names jsonb,
    mana_cost character varying(200),
    variations jsonb,
    image_url character varying(2000),
    watermark character varying(100),
    border character varying(20),
    timeshifted boolean,
    hand integer,
    life integer,
    reserved boolean,
    release_date character varying(50),
    starter boolean,
    rulings jsonb,
    foreign_names jsonb,
    printings jsonb,
    original_text text,
    original_type character varying(200),
    legalities jsonb,
    source text,
    multiverse_id integer
);

insert into cards_expanded
  (select card::json->>'name' as name, card::json->>'layout' as layout,
    cast(card::json->>'cmc' as numeric) as cmc, card::json->'colors' as colors,
    card::json->'colorIdentity' as color_identity, card::json->>'type' as type,
    card::json->'supertypes' as supertypes, card::json->'types' as types,
    card::json->'subtypes' as subtypes, card::json->>'rarity' as rarity,
    card::json->>'set' as set, card::json->>'set_name' as set_name,
    card::json->>'text' as text, card::json->>'flavor' as flavor,
    card::json->>'artist' as artist, card::json->>'number' as number,
    card::json->>'power' as power, card::json->>'toughness' as toughness,
    card::json->>'loyalty' as loyalty, card::json->'names' as names,
    card::json->>'manaCost' as mana_cost, card::json->'variations' as variations,
    card::json->>'imageUrl' as image_url, card::json->>'watermark' as watermark,
    card::json->>'border' as border,
    cast(coalesce(card::json->>'timeshifted', 'false') as boolean) as timeshifted,
    cast(card::json->>'hand' as int) as hand, cast(card::json->>'life' as int) as life,
    cast(coalesce(card::json->>'reserved','false') as boolean) as reserved,
    card::json->>'releaseDate' as release_date, cast(coalesce(card::json->>'starter','false') as boolean) as starter,
    card::json->'rulings' as rulings, card::json->'foreignNames' as foreign_names,
    card::json->'printings' as printings, card::json->>'originalText' as original_text,
    card::json->>'originalType' as original_type, card::json->'legalities' as legalities,
    card::json->>'source' as source from cards, cast(card::json->>'multiverseid' as int) as multiverse_id);